### ISSUE TITLE
What about SCJSS?

### ISSUE THREAD

**Issue by KargJonas** [cjss-group/CJSS#53]
I have a dream..
Imagine using SCSS to generate markdown and simultaniously applying styles/scripts to the elements:
```scss
div.root {
  padding: 5px;
  margin: 5px;
  border: 1px solid #000;

  h1 {
    innerHTML: "Welcome to SCJSS!";
    color: red;

    &:hover {
      script: js(console.log("You hovered over me!"));
    }
  }

  h3 {
    innerHTML: "Subtitle!";
  }
}
```
That ⬆️ turns into this ⬇️ :
```html
<div class="root">
  <h1>
    Welcome to SCJSS!;
  </h1>

  <h3>
    Subtitle!
  </h3>
</div>
```
(Plus the corresponding CSS and JS)
